### ISSUE TITLE
Redirect back to app after OIDC Login on Android doesn't work

### ISSUE THREAD

**Issue by mraible** [ruddell/ignite-jhipster#59]
To make my API work with Android in an emulator, I had to change all `localhost` links to `10.0.2.2`. See [emulator-networking](https://developer.android.com/studio/run/emulator-networking) for more information.

This means I had to update `src/main/resources/config/application.yml` in my JHipster app to the following.

```yaml
security:
    oauth2:
        client:
            access-token-uri: http://10.0.2.2:9080/auth/realms/jhipster/protocol/openid-connect/token
            user-authorization-uri: http://10.0.2.2:9080/auth/realms/jhipster/protocol/openid-connect/auth
            client-id: web_app
            client-secret: web_app
            scope: openid profile email
        resource:
            user-info-uri: http://10.0.2.2:9080/auth/realms/jhipster/protocol/openid-connect/userinfo
```

In my React Native app, I had to change my `apiUrl` in `App/Config/AppConfig.js`. 

```js
export default {
  apiUrl: 'http://10.0.2.2:8080/',
  appUrlScheme: 'healthpoints'
}
```

Then I modified my `android/app/src/main/AndroidManifest.xml` to contain my app's scheme.

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.healthpoints">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="healthpoints" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>
</manifest>
```

I ran `adb reverse tcp:9090 tcp:9090` so Reactotron works. 

I'm able to click **Login** and authenticate with Keycloak. However, when it redirects back to my app, I'm not authenticated and no access token is sent to the server. 

Here's an animated gif that shows this behavior.

![android oidc](https://user-images.githubusercontent.com/17892/46646410-54c34500-cb47-11e8-8655-0de6d39f3165.gif)

Here's a screenshot of Reactotron showing the redirect to the IdP and subsequent call to get account information w/o an access token.

![Reactotron](https://user-images.githubusercontent.com/17892/46646215-2bee8000-cb46-11e8-933c-2a9944497b34.png)
